CONFIG_TABLE='iot_config'
IOT_MAIN_TABLE='iot_main_table'
IOT_AGG_MAX_TABLE='iot_agg_max_table'
IOT_AGG_15_MINUTES_SUMMARY_TABLE='iot_agg_15_minutes_summary_table'
IOT_AGG_1_HOUR_SUMMARY_TABLE='iot_agg_1_hour_summary_table'
IOT_AGG_1_DAY_SUMMARY_TABLE='iot_agg_1_day_summary_table'
IOT_CRON_JOB_TABLE='iot_cron_job'
IOT_CRON_EXCEPTION='iot_cron_job_exception'

IOT_ASSET_MSTR='iot_asset_master'
IOT_LOCATION='iot_location'
IOT_ROLE='role'
IOT_APP_USER='iot_app_user'
Client='client'
Customer='customer'
Location='location'
